#!/bin/bash

#Clearnet IP vars

clear_ip=$(curl -s https://icanhazip.com)
clear_country=$(whois ${clear_ip} | grep -i country | nl | grep 1 | awk '{print $3}')

#Onion IP vars

onion_ip=$(proxychains4 -q curl -s https://icanhazip.com)

if [[ -z "${onion_ip}" ]]; then
	echo""
else
	onion_country=$(whois ${onion_ip} | grep -i country | nl | grep 1 | awk '{print $3}')
fi

#I2P IP vars

i2p_ip=$(proxychains4 -f ${HOME}/conf_files/proxychains/proxychains4alt.conf -q curl -s https://icanhazip.com)

if [[ -z "${i2p_ip}" ]]; then
	echo ""
else
	i2p_country=$(whois ${i2p_ip} | grep -i country | nl | grep 1 | awk '{print $3}')
fi

echo "-------"
echo "IP List"
echo "-------"

#Print Clearnet IP address

if [[ -n "${clear_ip}" ]]; then
	echo "Clearnet IP: ${clear_ip}/${clear_country}"
else
	echo "Clearnet IP not available"
fi

#Print Onion IP address

if [[ -n "${onion_ip}" ]]; then
	echo "Onion IP: ${onion_ip}/${onion_country}"
else
	echo "Onion IP not available"
fi

#Print I2P address

if [[ -n "${i2p_ip}" ]]; then
	echo "I2P IP: ${i2p_ip}/${i2p_country}"
else
	echo "I2P IP not available"	
fi
